name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Style checks
        run: ./mill __.checkFormat
      - name: Test
        run: |
          git config --global user.name "CI"
          ./mill -i itest
      - name: Publish
        if: github.ref == 'refs/heads/master' || github.event_name == 'release'
        run: |
          echo "${{secrets.pgp_secret_key}}" > private.key
          gpg --batch --yes --import private.key
          rm private.key

          ./mill mill.scalalib.PublishModule/publishAll --sonatypeCreds ${{secrets.sonatype_credentials}} --publishArtifacts __.publishArtifacts --awaitTimeout 600000 --release true
