name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Style checks
        run: ./mill _.checkFormat
      - name: Compile
        run: ./mill _.compile
