name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: ./mill show __.publishVersion
